name: linger
description: Linger App

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.0
  firebase_auth: ^0.5.10
  google_sign_in: ^3.0.3
  sqflite: any
  path_provider: ^0.4.0
  speech_recognition: "^0.2.0+1"
  # firebase_core: ^0.2.3
  # firebase_database: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/facebook.png
    - assets/google.png
    - assets/sdi.png
    - assets/bg/wood.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Trattatello
      fonts:
        - asset: assets/fonts/Trattatello.ttf
    - family: 'Brela'
      fonts:
        - asset: assets/fonts/Brela_Regular.otf
    - family: 'Fira Code'
      fonts:
        - asset: assets/fonts/FiraCode_Regular.ttf
        - asset: assets/fonts/FiraCode_Retina.ttf
    - family: 'Butler'
      fonts:
        - asset: assets/fonts/Butler_Regular.otf
        - asset: assets/fonts/Butler_Medium.otf
    - family: 'Crimson'
      fonts:
        - asset: assets/fonts/CrimsonText_Regular.ttf
        - asset: assets/fonts/CrimsonText_Italic.ttf
    - family: 'Jura'
      fonts:
        - asset: assets/fonts/Jura_Regular.ttf
        - asset: assets/fonts/Jura_Italic.ttf
          style: italic
  #       - asset: fonts/Schyler-Italic.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

